server:
  port: 7071

spring:
  application:
    name: @artifactId@

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8081/eureka/,http://eureka:eureka@localhost:8082/eureka/